### ISSUE TITLE
compoesr安装失败

### ISSUE THREAD

**Issue by MADAOCOO** [51idc/aliyun-openapi-php-sdk#5]
composer require anchnet/aliyun-openapi-php-sdk

 [InvalidArgumentException]
  Could not find package anchnet/aliyun-openapi-php-sdk at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by wudi** [comment]
`composer require anchnet/aliyun-openapi-php-sdk:dev-master`
